services:
  mkdocs:
    image: squidfunk/mkdocs-material:latest
    container_name: mkdocs

    working_dir: /docs

    volumes:
      - ./site:/docs

    ports:
      - "8000:8000"

    command: serve --dev-addr=0.0.0.0:8000

    restart: unless-stopped
